GAMES/urls.py
from django.template.defaulttags import url
from django.urls import path

from GAMES.views import home,games,match_home,scores,delete_noti,delete_game,match

app_name = "game"
urlpatterns = [
    path('', games, name='game'),
    path('matchs/', match_home, name='match_home'),
    path('scores/', scores, name='scores'),
    path('delete_noti/<id>',delete_noti,name='delete_noti'),
    path('delete_game/<id>',delete_game,name='delete_game'),
    path('matchs/<str:id>/', match, name='match'),
]

LTM/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import GAMES.views as gameviews
import Accounts.views as accountviews
app_name = "ltm"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', gameviews.home, name='home'),
    path('', gameviews.index, name='home'),
    path('games/', include('GAMES.urls')),
    path('accounts/', include('Accounts.urls')),
    path('channels/', include('Channels.urls')),
    path('notification/', gameviews.notification),
] + static("/media/", document_root="/home/copv/git/LTM/media/")

admin.site.site_header = "CYBORG Admin"
admin.site.site_title = "CTF"
admin.site.index_title = "CYBORG Admin Portal"

GAMES/models.py
from django.db import models
from Accounts.models import Users
from django.utils import timezone
# Create your models here.


class Game(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, unique=True)
    author = models.ForeignKey(Users, on_delete=models.CASCADE)
    ip = models.CharField(max_length=200, default='localhost')
    port = models.IntegerField(default=80)
    rule = models.FileField(upload_to='uploads/')
    is_active = models.BooleanField(default=True)
    STATUS = [
        (0, "off"),
        (1, "on")
    ]
    status = models.IntegerField(choices=STATUS, default=1)

    def __str__(self):
        return self.name+"_"+str(self.id)


class Match(models.Model):
    id = models.AutoField(primary_key=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE, default=0)
    id_play1 = models.IntegerField(blank=False)
    id_play2 = models.IntegerField(blank=False)
    score_play1 = models.IntegerField(default=0)
    score_play2 = models.IntegerField(default=0)
    date_create = models.DateTimeField(default=timezone.now)
    date_end = models.DateTimeField(default=timezone.now)
    password = models.CharField(max_length=50, blank=False, default='passwd')
    STATUS = [
        (0, "waiting"),
        (1, "running"),
        (2, "end"),
    ]
    history = models.FileField(upload_to='uploads/history/', blank=True)
    status = models.IntegerField(choices=STATUS, default=0)

    def __str__(self):
        return str(self.game)+"_"+str(self.id)


class Notification(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(Users, models.CASCADE)
    title = models.TextField()
    content = models.TextField()
    ip = models.TextField()
    port = models.IntegerField()
    passwd = models.TextField(default="passwd")

    def __str__(self):
        return str(self.user_id) + "_" + str(self.title)


class Scores(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(Users, models.CASCADE)
    game_id = models.ForeignKey(Game, on_delete=models.CASCADE)
    score = models.BigIntegerField(default=0)

    def __str__(self):
        return str(self.user_id) + "_" + str(self.game_id)

GAMES/forms.py
from django import forms
from django_registration.forms import RegistrationForm
from django import forms
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError
from numpy import require

from GAMES.models import *
from Accounts.models import Users


class CustomUserCreationForm(RegistrationForm):
    class Meta(RegistrationForm.Meta):
        model = Users
        fields = ('username', 'email', 'score')


class NewGameForm(forms.Form):
    error_messages = {
        "name_valid": (f'The name "%s" is not valid'),
        "id1_valid": (f'The id1 "%s" is not valid'),
        "id2_valid": (f'The id2 "%s" is not valid'),
    }
    name = forms.CharField(max_length=100)
    ip = forms.CharField(max_length=200)
    port = forms.IntegerField()
    rule = forms.FileField()

    def clean_rule(self):
        rule = self.cleaned_data.get("rule")
        return rule

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if Game.objects.filter(name=name).first() is not None:
            raise ValidationError(
                self.error_messages["email_valid"] % name,
                code="name_valid",
            )
        return name

    class Meta:
        model = Game


class MatchForm(forms.Form):
    error_messages = {
        "name_valid": (f'The name "%s" is not valid'),
        "id1_valid": (f'The id1 "%s" is not valid'),
        "id2_valid": (f'The id2 "%s" is not valid'),
    }
    game = forms.IntegerField()
    id_play1 = forms.IntegerField(required=True)
    id_play2 = forms.IntegerField(required=True)
    password = forms.CharField(max_length=50, required=True)

    def clean_game(self):
        game = self.cleaned_data.get("game")
        if Game.objects.filter(id=game).first() == None:
            raise ValidationError(
                self.error_messages["name_valid"] % game,
                code="game_valid",
            )
        return game

    def clean_id_play1(self):
        id = self.cleaned_data.get("id_play1")
        if id and Users.objects.filter(id=id).first() == None:
            raise ValidationError(
                self.error_messages["id1_valid"] % id,
                code="id1_valid",
            )
        return id
    def clean_id_play2(self):
        id = self.cleaned_data.get("id_play1")
        id2 = self.cleaned_data.get("id_play2")
        if id and id2 and id == id2:
            raise ValidationError(
                self.error_messages["id2_valid"],
                code="id1_valid",
            )
        if Users.objects.filter(id=id2).first() == None:
            raise ValidationError(
                self.error_messages["id2_valid"] % id2,
                code="id1_valid",
            )
        return id2
    class Meta:
        model = Match

GAMES/views.py
import websockets
import asyncio
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from asgiref.sync import sync_to_async, async_to_sync
from datetime import datetime, timedelta, timezone, tzinfo
from django.contrib import messages as mmesg
from pwn import *
import random
import json

# Create your views here.
from GAMES.models import Game, Match, Notification
from Accounts.models import Users
from django.core.exceptions import PermissionDenied
from .forms import NewGameForm, MatchForm
import json


def home(request):
    noti = Notification.objects.filter(user_id=request.user.id)
    return render(request, 'Games/home.html', {"notis": noti})


def games(request):
    if request.method == "POST":
        form = NewGameForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            ip = form.cleaned_data.get("ip")
            port = form.cleaned_data.get("port")
            rule = form.cleaned_data.get("rule")
            game = Game(name=name, author_id=request.user.id,
                        ip=ip, port=port, rule=rule)
            game.save()
        return redirect("accounts:profile")
    try:
        games = Game.objects.filter(author_id=request.GET['id'])
    except:
        games = Game.objects.all()
    form = MatchForm()
    users = Users.objects.all()
    return render(request, 'Games/games.html', {"games": games, "users": users, "form": form})


def match(request, id):
    match = Match.objects.filter(id=id).first()
    return render(request, 'Games/id.html', {
        'id': id,
        'match':match
    })


def delete_game(request, id):
    author = Game.objects.filter(id=id).first()
    if author != None:
        if request.user.is_superuser or (int(request.user.id) == int(Game.objects.filter(id=id).first().author_id)):
            Game.objects.filter(id=id).delete()
            return redirect("accounts:profile")
        else:
            raise PermissionDenied
    return render(request, 'Games/home.html')


def match_home(request):
    if request.method == "POST":
        form = MatchForm(request.POST)
        if form.is_valid():
            game = form.cleaned_data.get('game')
            id1 = form.cleaned_data.get('id_play1')
            id2 = form.cleaned_data.get('id_play2')
            if id1 == id2:
                mmesg.error(request, "2 users cannot overlap")
                return redirect("game:match_home")
            password = form.cleaned_data.get('password')
            g = Game.objects.filter(id=game).first()
            if g.status == 0:
                return redirect("game:match_home")
            match_id = Match.objects.all().order_by("-id").first().id
            match_id+=1
            data = {
                "action": 1,
                "match": match_id,
                "id1": id1,
                "id2": id2,
                "passwd": password
            }
            if g.ip[:5] == "ws://":
                try:
                    async def connect():
                        uri = g.ip + ":" + str(g.port)
                        async with websockets.connect(uri) as websocket:
                            async def send_hello():
                                # await asyncio.sleep(3)
                                await websocket.send(json.dumps(data))
                                # msg = (await json.loads(websocket.recv()))
                                # print(msg)

                            task = asyncio.create_task(send_hello())
                            msg = (await websocket.recv())
                            msg = json.loads(msg)
                            print(msg)
                            result = msg['result']
                            ip_connect = msg['ip']
                            port_connect = msg['port']
                            path_connect = msg['path']

                            if result == 1:
                                sync_to_async(Match(game_id=int(game), id_play1=id1, id_play2=id2, password=password,
                                                    date_create=datetime.now()).save())
                                mmesg.success(
                                    request, "Create a successful game")
                                sync_to_async(
                                    Notification(title=g.name, user_id_id=id1, ip=ip_connect, port=port_connect,
                                                 content="connect game %s with id match=%s, ip=%s, port=%s, path=%s" % (
                                                     g.name,
                                                     match_id, ip_connect,
                                                     port_connect, path_connect)).save())
                                sync_to_async(
                                    Notification(title=g.name, user_id_id=id2, ip=ip_connect, port=port_connect,
                                                 content="connect game %s with id match=%s, ip=%s, port=%s, path=%s" % (
                                                     g.name, match_id, ip_connect,
                                                     port_connect, path_connect)).save())
                            await task

                    asyncio.run(connect())
                    g.status = 0
                    g.save()

                except Exception as e:
                    print(e)
                    pass

            else:
                try:
                    req = remote(g.ip, g.port)
                    req.send(json.dumps(data).encode())
                    msg = json.loads(req.recv(1024).decode())
                    print(msg)
                    try:
                        message = msg['result']
                        ip_connect = msg['ip']
                        port_connect = msg['port']
                        path_connect = msg['path']
                        if message == 1:
                            Match(game_id=int(game), id_play1=id1, id_play2=id2, password=password,
                                  date_create=datetime.now()).save()
                            mmesg.success(request, "Create a successful game")
                            Notification(title=g.name, user_id_id=id1, passwd=password, ip=ip_connect,
                                         port=port_connect,
                                         content="connect game %s with id match=%s, ip=%s, port=%s, path=%s" % (g.name,
                                                                                                                match_id,
                                                                                                                ip_connect,
                                                                                                                port_connect,
                                                                                                                path_connect)).save()
                            Notification(title=g.name, user_id_id=id2, passwd=password, ip=ip_connect,
                                         port=port_connect,
                                         content="connect game %s with id match=%s, ip=%s, port=%s, path=%s" % (g.name,
                                                                                                                match_id,
                                                                                                                ip_connect,
                                                                                                                port_connect,
                                                                                                                path_connect)).save()

                        g.status = 0
                        g.save()
                        req.close()
                    except:
                        req.close()
                        mmesg.error(request, "Can't create match")
                    req.close()
                except:
                    mmesg.error(
                        request, "Can't connect to ip %s port %s" % (g.ip, g.port))
            return redirect("game:match_home")
    form = MatchForm()
    matchs = Match.objects.all().order_by("-date_create")
    try:
        matchs = matchs.filter(status=request.GET['type'])
    except:
        pass
    try:
        matchs = matchs.filter(game=request.GET['id'])
    except:
        pass
    for match in matchs:
        if match.status == 1:
            try:
                start = time.time()
                ip = Game.objects.filter(id=match.game_id).first().ip
                port = Game.objects.filter(id=match.game_id).first().port

                data = {
                    "result": 2,  # result = 3 là thông báo ván đấu kết thúc
                    # match sẽ là giá trị thông tin của match nào mà WS gửi lúc yêu cầu tạo match
                    "match": match.id,
                }
                if ip[:5] == "ws://":
                    address = f'%s:%s/' % (ip, port)
                    try:
                        async def hello():
                            async with websockets.connect(address) as websocket:
                                await websocket.send(json.dumps(data))
                    

                        asyncio.run(hello())
                        if time.time() - start:
                            break
                    except Exception as e:
                        print(e)
                        break
                else:
                    req = remote(ip, port)
                    req.send(json.dumps(data).encode())
                    req.close()
                    if time.time()-start:
                        break
            except:
                pass
    paginator = Paginator(matchs, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

templates/Games/games.html
{% extends "base.html" %}
{% block title %}
    Games
{% endblock title %}
{% block main %}
    <div class="container h-100 d-inline-block  mx-auto d-flex flex-column justify-content-center align-items-center text-center position-relative"
         data-aos="zoom-out">
        <div>
            <select onchange="games(this);" class="form-select" aria-label="Default select example">
                <option selected>Open this select game with user.</option>
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.username }}</option>
                {% endfor %}
            </select>
        </div>
        <table class="table table-hover bg-light">
            <thead>
            <tr class="text-danger">
                <th>Game</th>
                <th>Author</th>
                <th>Rule</th>
                <th>Status</th>
                <th style="width: 10%">Play</th>
            </tr>
            </thead>
            <tbody>
            {% for game in games %}
                <tr>
                    <td>{{ game.name }}</td>
                    <td>{{ game.author }}</td>
                    <td><a href="/media/{{ game.rule }}"><i class="fa fa-download"></i></a></td>
                    <td>{% if game.status == 0 %}Off{% else %}On{% endif %}</td>
                    <td>
                        {% if game.status == 1 %}
                        <button type="button" style="float: right" class="btn btn-primary float-right"
                                data-bs-toggle="modal"
                                onclick="play({{ game.id}},'{{ game.name }}')"
                                data-bs-target="#staticBackdrop">
                            Create Game
                        </button>
                        {% else %}
                            <button type="button" style="float: right" class="btn float-right btn btn-danger">
                                Create Game
                            </button>
                        {% endif %}
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1"
         aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="staticBackdropLabel">Create Game</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <div>Game: <b id="namegame"></b></div>
                    <form class=" mx-auto" action="/games/matchs/" method="post" id="createGame"
                          enctype="multipart/form-data">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                       <input type="hidden" name="game" id="id_game" value="">
                        <div id="div_id_id_play1" class="control-group"><label for="id_play1"
                                                                               class="control-label requiredField">
                            ID 1<span class="asteriskField">*</span> </label>
                            <div class="controls w-100">{{ form.id_play1|linebreaks }}</div>
                        </div>
                        <div id="div_id_id_play2" class="control-group"><label for="id_play2"
                                                                               class="control-label requiredField">
                            ID 2<span class="asteriskField">*</span> </label>
                            <div class="controls w-100">{{ form.id_play2|linebreaks }}</div>
                        </div>
                        <div id="div_id_password" class="control-group"><label for="password"
                                                                               class="control-label requiredField">
                            password<span class="asteriskField">*</span> </label>
                            <div class="controls w-100">{{ form.password|linebreaks }}</div>
                        </div>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <input type="submit" id="submit" data-bs-dismiss="modal" class="btn btn-primary"
                               value="New Match">
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script>
        function play(id,name) {
            document.getElementById("namegame").innerText = name;
            document.getElementById("id_game").value = id;

        };

        function games(obj) {
            location = "/games/?id=" + obj.value;
        }
    </script>
{% endblock main %}

templates/Games/home.html
{% extends "base.html" %}
{% block title %}
    Home
{% endblock title %}
{% block demo %}
    <section id="hero-animated" class="hero-animated d-flex align-items-center">
    <div class="container d-flex flex-column justify-content-center align-items-center text-center position-relative"
         data-aos="zoom-out">
        <img src="../static/assets/img/hero-carousel/hero-carousel-3.svg" class="img-fluid animated">
        <h2>Welcome to <span>Cyborg</span></h2>
{#        <p>Et voluptate esse accusantium accusamus natus reiciendis quidem voluptates similique aut.</p>#}
        <div class="d-flex">
            <a href="#about" class="btn-get-started scrollto">Get Started</a>
            <a href="https://www.youtube.com/watch?v=LXb3EKWsInQ"
               class="glightbox btn-watch-video d-flex align-items-center"><i class="bi bi-play-circle"></i><span>Watch Video</span></a>
        </div>
    </div>
</section>
{% endblock demo %}

templates/Games/id.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock title %}
{% block main %}
<div class="container text-center">
    <div class="most-popular" style="background-color: #bebebf">
        <div class="row">
                <div class="item margin-top" style="background-color: #344D67">
                    <a href="/games/matchs/{{match.id}}">
                        <h5>Match ID: </h5><h5 id="match_id">{{ match.id }}</h5>
                    </a>
                    <h4 style="color: #e54d07; text-transform:uppercase" >{{ match.game.name }}<br><span id="status">
                            {% if match.status == 0 %}
                            waiting
                            {% elif match.status == 1 %}
                            running
                            {% else %}
                            end
                            {% endif %}
                        </span></h4>
                    <ul style="width:30%">
                        <li style="text-align: left;"><i class="fa " style=" color: red" id="score_id1">{{match.score_play1}}</i></li>
                        <li style="text-align: left;"><i class="fa " style=" color: red" id="score_id2">{{ match.score_play2 }}</i>
                        </li>
                    </ul>
                    <ul style="width:30%">
                        <li style="text-align: left"><i class="fa ">UID&nbsp;1&nbsp;: {{ match.id_play1 }}&nbsp;</i>
                        </li>
                        <li style="text-align: left"><i class="fa ">UID
                                2&nbsp;: {{ match.id_play2 }}&nbsp;</i>
                        </li>
                    </ul>

                </div>

        </div>
    </div>
</div>
<script>
    const roomName = document.getElementById("match_id").textContent;
    console.log(roomName)

    const chatSocket = new WebSocket(
        'ws://'
        + window.location.host
        + '/ws/channels/'
        + roomName
        + '/'
    );

    // onmessage - An event listener to be called when a message is received from the server.
    chatSocket.onmessage = function(e) {
        // JSON.parse() converts the JSON object back into the original object,
        // then examine and act upon its contents.
        const data = JSON.parse(e.data);
        document.querySelector('#score_id1').innerHTML = (data.id1);
        document.querySelector('#score_id2').innerHTML = (data.id2);
        if(data.status==0){
            document.querySelector('#status').innerHTML = "WAITING";
        }else if(data.status==1){
            document.querySelector('#status').innerHTML = "RUNNING";
        }
        else if(data.status==2){
            document.querySelector('#status').innerHTML = "END";
        }

    }; 

    // onclose - An event listener to be called when the connection is closed.

    function autorun(e) {

        // Send the msg object as a JSON-formatted string.
        chatSocket.send(JSON.stringify({
            'message': "update"
        }));
            
        // Blank the text input element, ready to receive the next line of text from the user.
    };
    var myVar = setInterval(autorun, 400);
</script>

{% endblock main %}

templates/Games/notification.html
{% extends "base.html" %}
{% block title %}
    Notification
{% endblock title %}
{% block main %}
    <div class="container h-100 d-inline-block  mx-auto d-flex flex-column justify-content-center align-items-center text-center position-relative"
         data-aos="zoom-out">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col" style="width: 10%">IP</th>
                <th scope="col" style="width: 40%">Text</th>

                <th scope="col" style="width: 100px">Port</th>
                <th scope="col" style="width: 100px">Password</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for noti in notis %}
                <tr class="text-light">
                    <th scope="row">{{ noti.id }}</th>
                    <td>{{ noti.title }}</td>
                    <td>{{ noti.ip }}</td>
                    <td>{{ noti.content}}</td>
                    <td>{{ noti.port }}</td>
                    <td>{{ noti.passwd }}</td>
                    <td onclick="Delete(this.parentElement)"><button>Delete</button></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
<script>
function Delete(obj){
    location="/games/delete_noti/"+obj.firstElementChild.textContent
}
</script>
{% endblock main %}

templates/Games/scores.html
{% extends "base.html" %}
{% block title %}
    Scores
{% endblock title %}